name: Docker Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build
      env:
        IMPLARIO_REPO_USER: ${{ secrets.IMPLARIO_REPO_USER }}
        IMPLARIO_REPO_PASSWORD: ${{ secrets.IMPLARIO_REPO_PASSWORD }}
    - uses: actions/upload-artifact@v2
      with:
        name: squid-game-plugin
        path: node/build/libs/squid-game.jar
    - uses: actions/upload-artifact@v2
      with:
        name: squid-game-mod
        path: mod/build/libs/mod-bundle.jar
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: squid-game-plugin
      - uses: actions/download-artifact@v2
        with:
          name: squid-game-mod
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@17f28ab24d0d2832d5ff23a1409bbfc373ebcb96
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@2cad85de2462ab92a22ff973a347fb25c91d6082
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@fe02965b4878556fce19e4f0aa608d7d09ed629b
        with:
          build-args: |
            IMPLARIO_REPO_USER=${{ secrets.IMPLARIO_REPO_USER }}
            IMPLARIO_REPO_PASSWORD=${{ secrets.IMPLARIO_REPO_PASSWORD }} 
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
