name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --build-arg IMPLARIO_REPO_USER=${{secrets.IMPLARIO_REPO_USER}} --build-arg IMPLARIO_REPO_PASSWORD=${{secrets.IMPLARIO_REPO_PASSWORD}} --file Dockerfile --tag squid-game:$(date +%s)
